name: Pretty gay tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang mold libcunit1-dev
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: Run norminette
        run: |
          norminette --use-gitignore

      - name: Build and test
        run: |
          make shared
          make test

      - name: Package artifacts
        run: |
          XZ_OPT=-9 tar -Jcvf build-artifacts.tar.xz target

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build-artifacts.tar.xz
          retention-days: 1
