name: CI/CD Pipeline with Extended Testing
permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
      - include/**
      - tests/**
      - Makefile
      - .github/workflows/*.yml
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        compiler: [clang, gcc]
        linker: [mold, lld, default]
        include:
          - compiler: clang
            cc_package: clang
          - compiler: gcc
            cc_package: gcc
        exclude:
          - compiler: gcc
            linker: mold

    env:
      CC: ${{ matrix.compiler }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.linker }}-${{ hashFiles('Makefile') }}

      - name: Install toolchain
        run: |
          sudo ln -sf /bin/true /usr/bin/mandb
          sudo apt-get update -qq
          sudo apt-get install -yq --no-install-recommends ${{ matrix.cc_package }}
          case "${{ matrix.linker }}" in
            "mold") sudo apt-get install -yq mold ;;
            "lld") sudo apt-get install -yq lld ;;
          esac

      - name: Build project
        run: make CC=${{ matrix.compiler }} -j$(nproc)

      - name: Run core tests
        run: make test -j$(nproc)

      - name: Setup complexity tester
        run: |
          git clone --branch v2 https://github.com/SimonCROS/push_swap_tester
          cd push_swap_tester
          make -j$(nproc)

      - name: Get 42 checker
        run: |
          curl -so checker_linux https://cdn.intra.42.fr/document/document/28289/checker_linux
          chmod +x checker_linux

      - name: Execute complexity tests
        run: |
          THREADS=$(nproc)
          ./push_swap_tester/complexity -t $THREADS -f ./push_swap -o test_result1.log 100 500 1100 ./checker_linux
          ./push_swap_tester/complexity -t $THREADS -f ./push_swap -o test_result2.log 500 500 7700 ./checker_linux
